site_name: ポートフォリオ & アウトプット
site_description: プログラミング関連のアウトプット
site_author: Fukutaro matsuo
copyright: Copyright &copy 2020 Fukutaro matsuo

theme:
  name: material
  features:
    - navigation.instant
  language: ja
  logo: img/icon.png
  favicon: img/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: indigo
    accent: amber
  font:
    text: Noto Sans
    code: Inconsolata

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.caret

extra_css:
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  - "css/custom.css"

extra:
  search:
    language: "jp"

google_analytics:
  - "UA-165840169-2"
  - "auto"

nav:
  - 自己紹介: index.md
  - 便利コマンド: linux_command.md
  - Git/GitHub:
      - 疑似チーム開発フロー: git_team_development.md
      - アプリの複製と初期化: git_clone_and_git_init.md
  - Docker:
      - Rails + Postgres: docker_rails_postgres.md
      - Rails-api + Nuxt.js + Mysql: docker_rails_nuxt_mysql.md
      - MkDocs(docker-compose): mkdocs.md
  - AWS:
      - SAA試験概要: saa.md
      - ネットワーク基礎: network.md
      - VPC: vpc.md
      - EC2: ec2.md
      - S3: s3.md
      - IAM: iam.md
      - RDS: rds.md
      - ELB: elb.md
      - CloudWatch: cloudwatch.md
      - AutoScaling: autoscaling.md
      - CloudFront: cloudfront.md
      - CloudFormation: cloudformation.md
      - データベース: database.md
      - サーバレス: serverless.md
  - Ruby on Rails:
      - マイグレーション: migration.md
      - Devise: devise関連.md
  - Error解決:
      - 概要: error.md
      - 開発環境と本番環境でのdb:resetとdb:migrate: 開発環境と本番環境でのdb:resetとdb:migrate.md
      - docker-compose + MySQL でのパスワード入力時のエラー: docker-compose+mysqlでのパスワード入力時のエラー.md
      - credentials.ymlとmaster.keyの関係: rails_credentials_yml_and_master_key.md
