site_name: ポートフォリオ & アウトプット
site_description: ポートフォリオ & アウトプット
site_author: Fukutaro matsuo
copyright: Copyright &copy 2020 Fukutaro matsuo

theme:
  name: material
  language: ja
  logo: img/icon.png
  favicon: img/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: preference
    primary: indigo
    accent: amber
  font:
    text: Noto Sans
    code: Inconsolata

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

extra:
  search:
    language: "jp"

nav:
  - 自己紹介ページ: index.md
  - 技術メモ:
      - 環境構築:
          - Docker + Rails + Postgres: docker_rails_postgres.md
          - Docker + Rails-api + Nuxt.js + Mysql: docker_rails_nuxt_mysql.md
      - マイグレーション: migration.md
      - Devise: devise関連.md
      - 便利コマンド: convenient_command.md
  - エラー解決:
      - 開発環境と本番環境でのdb:resetとdb:migrate: 開発環境と本番環境でのdb:resetとdb:migrate.md
      - docker-compose + MySQL でのパスワード入力時のエラー: docker-compose+mysqlでのパスワード入力時のエラー.md
