site_name: ポートフォリオ & アウトプット
site_description: ポートフォリオ & アウトプット
site_author: Fukutaro matsuo
copyright: Copyright &copy 2020 Fukutaro matsuo

theme:
  name: material
  features: navigation.tabs
  language: ja
  logo: img/icon.png
  favicon: img/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: indigo
    accent: amber
  font:
    text: Noto Sans
    code: Inconsolata

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.caret

extra:
  search:
    language: "jp"

nav:
  - 自己紹介: index.md
  - 技術メモ:
      - 環境構築:
          - Docker + Rails + Postgres: docker_rails_postgres.md
          - Docker + Rails-api + Nuxt.js + Mysql: docker_rails_nuxt_mysql.md
          - MkDocs(Docker + docker-compose): mkdocs.md
      - マイグレーション: migration.md
      - Devise: devise関連.md
      - 便利コマンド: linux_command.md
  - エラー解決:
      - 開発環境と本番環境でのdb:resetとdb:migrate: 開発環境と本番環境でのdb:resetとdb:migrate.md
      - docker-compose + MySQL でのパスワード入力時のエラー: docker-compose+mysqlでのパスワード入力時のエラー.md
